main:
  params: [args]
  steps:
    - init:
        assign:
          - project_id: "zm-vertexai-test01"
          - service_name: "aiplatform.googleapis.com"
          - action: ${args.action} # 传入 "enable" 或 "disable"
          
    - toggleVertexAI:
        call: http.post
        args:
          url: ${"https://serviceusage.googleapis.com/v1/projects/" + project_id + "/services/" + service_name + ":" + action}
          auth:
            type: OAuth2
        result: toggleResult

    - returnResult:
        return: ${toggleResult}
